name: repo-checks

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  main:
    name: ruby-matrix-mysql
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRES_PORT: 5432
      PGPASSWORD: postgres
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    strategy:
      fail-fast: true
      matrix:
        wahwah:
          - 'assets:precompile'
          - 'brakeman'
          - 'rubocop'
          - 'flay'
          - 'bundle_audit'
        run: [ 'echo "$TASK"' ]
        db: ['']
        include:
          - name: 'aaa'
            task: 'db:create test:migrate_without_plugins'
            run: |
              export PLUGINS='' DATABASE_URL=mysql2://travis@127.0.0.1/samson_test?reconnect=true BUNDLE_WITHOUT=postgres:sqlite USE_UTF8MB4=1 SILENCE_MIGRATIONS=1
            db: mysql no plugin
          - name: 'bbb'
            task: 'db:create db:migrate default'
            run: |
              export DATABASE_URL=mysql2://travis@127.0.0.1/samson_test?reconnect=true BUNDLE_WITHOUT=postgres:sqlite USE_UTF8MB4=1 SILENCE_MIGRATIONS=1
              # bundle exec rake $TASK
            db: mysql
          - name: 'ccc'
            task: 'db:create db:migrate default'
            run: |
              export DATABASE_URL=postgresql://postgres@127.0.0.1/samson_test BUNDLE_WITHOUT=mysql:sqlite SILENCE_MIGRATIONS=1
              # bundle exec rake $TASK
            db: postgres
          - name: 'ddd'
            task: 'db:create db:migrate default'
            run: |
              export DATABASE_URL=sqlite3://null$PWD/db/test.sqlite3 BUNDLE_WITHOUT=postgres:mysql SILENCE_MIGRATIONS=1
              # bundle exec rake $TASK
            db: sqlite3
          - name: 'eee'
            task: fossa
            run: |
              export BINDIR=$(pwd) && curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
              ([[ -z "$FOSSA_API_KEY" ]] && [[ "$GITHUB_EVENT_NAME" != "pull_request" ]]) || (./fossa init && ./fossa analyze)
    steps:
    - name: Boomba ${{ matrix.task }} ${{ matrix.db }}
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        TASK: ${{ matrix.task }}
      run: |
        ${{ matrix.run }}
